accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'), #회원가입
    path('login/', login_check, name='login'), #로그인
    path('logout/', logout, name='logout'), #로그아웃
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('post/', include('post.urls', namespace='post')),
    path('', lambda r: redirect('post:post_list'), name='root') # 루트로 연결
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('new', post_new, name='post_new'),
    path('edit/<int:pk>/', post_edit, name='post_edit'),
    path('delete/<int:pk>/', post_delete, name='post_delete'),
    
    path('like', post_like, name='post_like'),
    path('bookmark', post_bookmark, name='post_bookmark'),
    
    path('comment/new', comment_new, name='comment_new'),
    path('commnet/delete', comment_delete, name='comment_delete'),
]

accounts/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField #이미지 처리
from imagekit.processors import ResizeToFill

def user_path(instance, filename):
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1] # 확장자 부분 가져오기
    return 'accouts/{}/{}.{}'.format(instance.user.username, pid, extension)


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField('별명', max_length=20, unique=True) # unique=True: 중복허용x
    picture = ProcessedImageField(upload_to=user_path,
                                  processors=[ResizeToFill(150, 150)], # 이미지 사진 조절
                                  format='JPEG',
                                  options={'quality': 90},
                                  blank=True,
                                 )
    about = models.CharField(max_length=300, blank=True) # 자기소개 부분
    GENDER_C = ( # gender select 하기
        ('선택안함', '선택안함'),
        ('여성', '여성'),
        ('남성', '남성'),
    )
    gender = models.CharField('성별(선택사항)',
                             max_length=10,
                             choices=GENDER_C,
                             default='N')
    
    def __str___(self):
        return self.nickname # nickname을 대표로 함

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth.models import User # 장고에 내장되어 있는 User

class LoginForm(forms.ModelForm): # 로그인 폼
    class Meta:
        model = User
        fields = ['username', 'password']


class SignupForm(UserCreationForm): # 회원가입 폼
    username = forms.CharField(label='사용자명', widget=forms.TextInput(attrs={
        'pattern': '[a-zA-Z0-9]+',
        'title': '특수문자, 공백 입력불가'
    }))
    
    nickname = forms.CharField(label='닉네임')
    picture = forms.ImageField(label='프로필 사진', required=False)
    
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)
    
    def clean_nickname(self): #유효성 검사 # 이미 존재하는 닉네임인지 확인
        nickname = self.cleaned_data.get('nickname')
        if Profile.objects.filter(nickname=nickname).exists():
            raise forms.ValidationError('이미 존재하는 닉네임 입니다')
        return nickname
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        User = get_user_model()
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('사용중인 이메일 입니다')
        return email
    
    def clean_picture(self):
        picture = self.cleaned_data.get('picture')
        if not picture:
            picture = None
        return picture
    
    def save(self):
        user = super().save()
        Profile.objects.create(
            user = user, # username, password
            nickname = self.cleaned_data['nickname'],
            picture = self.cleaned_data['picture']
        )
        return user

accounts/views.py
from django.contrib.auth import authenticate, login # authenticate:인증관련
from django.shortcuts import redirect, render
from django.contrib.auth import logout as django_logout
from .forms import SignupForm, LoginForm # 회원가입폼, 로그인폼

# Create your views here.

def signup(request): # 회원가입
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            print(form.cleaned_data)
            user = form.save()
            return redirect('accounts:login') # accounts의 login으로 redirect하기
    else: # get 요청일때
        form = SignupForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_check(request): # 로그인
    if request.method == "POST":
        form = LoginForm(request.POST)
        name = request.POST.get('username')
        pwd = request.POST.get('password')
        
        user = authenticate(username=name, password=pwd)
        
        if user is not None: # user가 데이터베이스에 있다면
            login(request, user) # 장고가 제공하는 기능 login
            return redirect("/")
        else:
            return render(request, 'accounts/login_fail.html')
    else: ## request.method != "GET"
        form = LoginForm() # 다시 로그인 시도
        return render(request, 'accounts/login.html', {"form": form})
    
    
def logout(request): # 로그아웃
    django_logout(request) # 장고에서 제공
    return redirect("/")
        
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

accounts/templates/accounts/login.html
{% extends "accounts/layout.html" %}

{% block content %}

<div id="main_container">

        <div class="form_container">

            <div class="form">


                <h1 class="sprite_insta_big_logo title"></h1>

                <form method="POST" action="{% url 'accounts:login' %}">
                    {% csrf_token %}
                    
                    <p class="login_user_name">
                        <label for="id_username">사용자명:</label>
                        <input id="{{ form.username.id_for_label }}" maxlength="15" name="{{ form.username.html_name }}">
                    </p>

                    <p class="login_user_password">
                        <label for="id_username">비밀번호:</label>
                        <input id="{{ form.password.id_for_label }}" maxlength="15" name="{{ form.password.html_name }}" type="password">
                    </p>

                    <input class="submit_btn" type="submit" value="로그인">
                </form>



            </div>

            <div class="bottom_box">
                <div>
                    <span>아이디가 없으신가요?</span><a href="{% url 'accounts:signup' %}">회원가입</a>
                </div>
            </div>


        </div>

    </div>

{% endblock %}

accounts/templates/accounts/login_fail.html
{% extends "accounts/layout.html" %}

{% block content %}

<div id="main_container">

        <div class="form_container">

            <div class="form">


                <h1 class="sprite_insta_big_logo title">
                    로그인에 실패하셨네요 ㅠ ㅠ :)
                </h1>
                <p>
                    아이디가 없다면 회원가입을 해주세요
                </p>



            </div>

            <div class="bottom_box">
                <div>
                    <span>아이디가 없으신가요?</span><a href="#">회원가입</a>
                </div>
            </div>


        </div>

    </div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/layout.html" %}

{% block content %}

<div id="main_container">

        <div class="form_container">

            <div class="form">



                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                       {{ form.as_p }}
                    <input class="submit_btn" type="submit" value="가입">
                    
                </form>



            </div>

            <div class="bottom_box">
                <div>
                    <span>아이디가 있다면</span><a href="#">로그인</a>
                </div>
            </div>


        </div>

    </div>

{% endblock %}