config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('post/', include('post.urls', namespace='post')),
    path('', lambda r: redirect('post:post_list'), name='root') # 루트로 연결
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('new', post_new, name='post_new'),
    path('edit/<int:pk>/', post_edit, name='post_edit'),
    path('delete/<int:pk>/', post_delete, name='post_delete'),
    
    path('like', post_like, name='post_like'),
    path('bookmark', post_bookmark, name='post_bookmark'),
    
    path('comment/new', comment_new, name='comment_new'),
    path('commnet/delete', comment_delete, name='comment_delete'),
]

post/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.

def photo_path(instance, filename):
    from time import strftime
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return '{}/{}/{}.{}'.format(strftime('post/%Y/%m/%d/'), instance.author.username, pid, extension)


# 게시글 모델 구현
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = ProcessedImageField(upload_to = photo_path,
                               processors=[ResizeToFill(600,600)],
                               format = 'JPEG',
                               options={'quality': 90})
    content = models.CharField(max_length=140, help_text="최대길이 140자 입력이 가능합니다")
    
    # many-to-many model 연결시키기
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                          blank=True,
                                          related_name='like_user_set',
                                          through='Like') # post.like_set 으로 접근 가능
    
    bookmark_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                              blank=True,
                                              related_name='bookmark_user_set',
                                              through='Bookmark') # post.bookmark_set 으로 접근 가능
    
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    class Meta:
        ordering = ['-created_at'] # 정렬: 최신순으로
        
    @property
    def like_count(self):
        return self.like_user_set.count()
    
    @property
    def bookmark_count(self):
        return self.bookmark_user_set.count()
    
        
    def __str__(self):
        return self.content

    
    
# 좋아요 모델 구현
class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 좋아요를 누른 user인가?
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = (
            ('user', 'post')
        )
        

        
# 북마크 모델 구현
class Bookmark(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 북마크를 누른 user인가?
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = (
            ('user', 'post')
        )
        
        

# 댓글 모델 구현
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE) # comment에 해당하는 post
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # comment의 작성자
    content = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-id']
        
    def __str__(self):
        return self.content
    

post/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    photo = forms.ImageField(label='', required=False) # required=False : 중복x
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'class': 'post-new-content',
        'rows': 5,
        'cols': 50,
        'placeholder': '140자 까지 등록 가능합니다'
    }))
    
    class Meta:
        model = Post
        fields = ['photo', 'content']
        
    
class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.TextInput(attrs={
        'class': 'comment-form',
        'size': '70px',
        'placeholder': '댓글 달기...',
        'maxlength': '40',
    }))
    
    class Meta:
        model = Comment
        fields = ['content']

post/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
import json
from django.http import HttpResponse
from .models import Post, Like, Comment
from .forms import PostForm


# Create your views here.

def post_list(request):
    
    post_list = Post.objects.all()
    
    if request.user.is_authenticated:
        username = request.user
        user = get_object_or_404(get_user_model(), username=username)
        # 여기까지는 장고 내장모델 model 을 찾는 과정
        user_profile = user.profile
        # 정의해둔 모델 profile에서 해당 데이터 찾기
        
        return render(request, 'post/post_list.html', {
            'user_profile': user_profile,
            'posts': post_list,
        })
    else:
        return render(request, 'post/post_list.html', {
            'posts': post_list,
        })
    
    
@login_required
@require_POST
def post_like(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    post_like, post_like_created = post.like_set.get_or_create(user=request.user)
    
    if not post_like_created:
        post_like.delete()
        message = "좋아요 취소"
    else:
        message = "좋아요"
        
    context = {'like_count': post.like_count,
              'message': message}
    
    return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
@require_POST
def post_bookmark(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    post_bookmark, post_bookmark_created = post.bookmark_set.get_or_create(user=request.user)
    
    if not post_bookmark_created:
        post_bookmark.delete()
        message = "북마크 취소"
    else:
        message = "북마크"
    
    context = {'bookmark_count': post.bookmark_count,
              'message': message}
    
    return HttpResponse(json.dumps(context), content_type="application/json")
        
        

@login_required #로그인이 되어있어야만 실행됨
def post_new(request):
    if request.method == 'POST':
        PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False) # 중복방지
            post.author = request.user
            post.save()
            #post.tag_save()
            messages.info(request, '새 글이 등록되었습니다')
            return redirect('post:post_list')
    else:
        form = PostForm()
        return render(request, 'post/post_new.html', {'form': form})
    

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        messages.warning(request, '잘못된 접근입니다')
        return redirect('post:post_list')
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            #post.tag_set.clear()
            #post.tag_save()
            #messages.success(request, '수정완료')
            return redirect('post:post_list')
    else: # get방식일때
        form = PostForm(instance=post)
    return render(request, 'post/post_edit.html', {
        'post': post,
        'form': form,
    })
            
            
@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user or request.method == 'GET':
        #messages.warning(request, '잘못된 접근입니다.')
        return redirect('post:post_list')
    
    if request.method == 'POST':
        post.delete()
        #messages.success(request, '삭제완료')
        return redirect('post:post_list')
    
    


@login_required
def comment_new(request): # ajax로 댓글을 추가할 때 처리하기
    pk = request.POST.get('pk')
    post = get_object_or_404(Post, pk=pk) # pk로 댓글에 대한 Post 찾기
    if request.method == 'POST': # ajax에서 전달한 요청이 post일때
        form = CommentForm(request.POST) # 사용자가 작성한 댓글폼을 post로 가져옴
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return render(request, 'post/comment_new_ajax.html', {
                'comment': comment,
            })
    return redirect("post:post_list")


@login_required
def comment_delete(request): # ajax로 댓글에 대한 삭제 요청이 들어왔을 때 처리하기
    pk = request.POST.get('pk')
    comment = get_object_or_404(Comment, pk=pk) # 해당 삭제할 댓글을 가져오기
    if request.method == 'POST' and request.user == comment.author:
        comment.delete()
        message = '삭제완료'
        status = 1
    else:
        message = '잘못된 접근입니다'
        status = 0
    
    return HttpResponse(json.dumps({'message': message, 'status': status, }), content_type="application/json")


        
    

post/templates/post/layout.html
{% extends "layout.html" %}

post/templates/post/post_edit.html
{% extends "post/layout.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/new_post.css' %}">
{% endblock %}



{% block content %}
<div id="main_container">
    <div class="post_form_container">
        <form action="#" class="post_form" method="post" enctype="multipart/form-data">
            <div class="title">
                Edit Post
            </div>
            <div class="preview">
                <div class="upload">
                    <div class="post_btn">
                        {% if post %}
                            <p><img id="img_id" src="{{ post.photo.url }}" style="width: 300px; height: 300px;
                                object-fit: cover"></p>
                        {% endif %}
                    </div>
                </div>
            </div>
            
            {% csrf_token %}
            {{ form.as_p }}
            
            <input class="submit_btn" type="submit" value="수정완료">       
        </form>
    </div>
</div>
<script>
    const photo = document.querySelector('#img_id');
    document.querySelector('#photo-clear_id').remove();
    document.querySelector("label[for='photo-clear_id']").remove();
    
    function upload_img(input){
        var reader = new FileReader();
        if(input.files && input.files[0]){
            reader.onload = function(e){
                photo.setAttribute('src',e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    
    let idPhoto = document.querySelector('#id_photo');
    
    idPhoto.addEventListener('change',function(){
        upload_img(this);
    });
</script>



















{% endblock %}

post/templates/post/post_list.html
{% extends 'post/layout.html' %}
{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/common.css' %}">

{% endblock %}

{% block content %}

<section id="main_container">
        <div class="inner">

            <div class="contents_box">
                {% for post in posts %}
                <article class="contents">
                    <header class="top">
                        <div class="user_container">
                            <div class="profile_img">
                                {% if post.author.profile.picture %}
                                <img src="{{ post.author.profile.picture.url }}" alt="프로필이미지">
                                {% else %}
                                <img src="{% static 'imgs/thumb.jpeg' %}" alt="프로필이미지">
                                {% endif %}
                            </div>
                            <div class="user_name">
                                <div class="nick_name m_text">{{ post.author.profile.nickname }} {{ post.id }}</div>
                                <div class="country s_text">Seoul, South Korea</div>
                            </div>
                            
                            <div>
                                <form action="{% url 'post:post_delete' post.pk %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" value="삭제">
                                </form>
                            </div>

                        </div>

                        <div class="sprite_more_icon" data-name="more">
                            <ul class="toggle_box">
                               <li><input type="submit" class="follow" value="팔로우" data-name="follow"></li>
                                <li>수정</li>
                                <li>삭제</li>
                            </ul>
                        </div>
                    </header>

                    <div class="img_section">
                        <div class="trans_inner">
                            <div><img src="{{ post.photo.url }}" alt="visual01"></div>
                        </div>
                    </div>

                    <div class="bottom_icons">
                        <div class="left_icons">
                            <div class="heart_btn">
                                {% if user in post.like_user_set.all  %}
                                <div class="sprite_heart_icon_outline on" name="{{ post.id }}" data-name="heartbeat"></div>
                                {% else %}
                                <div class="sprite_heart_icon_outline" name="{{ post.id }}" data-name="heartbeat"></div>
                                {% endif %}
                            </div>
                            <div class="sprite_bubble_icon"></div>
                            <div class="sprite_share_icon" data-name="share"></div>
                        </div>
                        <div class="right_icon">
                            {% if user in post.bookmark_user_set.all %}
                            <div class="sprite_bookmark_outline on" name="{{ post.id }}" data-name="bookmark"></div>
                            {% else %}
                            <div class="sprite_bookmark_outline" name="{{ post.id }}" data-name="bookmark"></div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="likes m_text">
                        
                        <span id="like-count-{{ post.id }}">좋아요{{ post.like_count }}개</span>
                        <span id="bookmark-count-{{ post.id }}">북마크{{ post.bookmark_count }}개</span>
        
                    </div>

                    <div class="comment_container">
                        <div class="comment" id="comment-list-ajax-post{{post.id}}">
                            {% for comment in post.comment_set.all %}
                            <div class="comment-detail" id="comment{{ comment.id }}">
                                
                                
                                <div class="nick_name m_text">{{ comment.author.profile.nickname }}</div>
                                <div>{{ comment.content }}</div>
                                {% if user == comment.author %}
                                    <input type="button" class="del-comment" data-name="comment_delete" value="삭제" name="{{ comment.id }}">
                                {% endif %}
                            </div>
                            {% endfor %}
                        </div>
                        
                        <div class="small_heart">
                            <div class="sprite_small_heart_icon_outline"></div>
                        </div>
                    </div>

                    <div class="timer">{{ post.created_at|timesince }}</div>

                    <div class="comment_field" id="add-comment-post{{post.id}}">
                        {% if user.is_authenticated %}
                        {{ comment_form }}
                        <input type="text" placeholder="댓글달기...">
                        <div class="upload_btn m_text" name="{{post.id}}" data-name="comment">게시</div>
                        {% else %}
                        {{ comment_form }}
                        <input type="text" placeholder="댓글달기...">
                        <div class="upload_btn m_text" name="{{post.id}}" data-name="comment" onclick="alert('댓글을 작성하려면 로그인이 필요합니다')">게시</div>
                        {% endif %}
                    </div>
                </article>
                {% endfor %}
            </div>
            
            <input type="hidden" id="page" value="2">

            <div class="side_box">
                {% if user_profile %}
                <div class="user_profile">
                    <div class="profile_thumb">
                        <img src="{{ user_profile.picture.url }}" alt="프로필사진">
                    </div>
                    <div class="detail">
                        <div class="id m_text">{{ user_profile.user }}</div>
                        <div class="ko_name">{{ user_profile.nickname }}</div>
                    </div>
                </div>
                {% else %}
                <div class="user_profile">
                    <div class="profile_thumb">
                        <img src="{% static 'imgs/thumb.jpeg' %}" alt="프로필사진">
                    </div>
                    <div class="detail">
                    </div>
                </div>
                {% endif %}

                <article class="story">
                    <header class="story_header">
                        <div>스토리</div>
                        <div class="more">모두 보기</div>
                    </header>

                    <div class="scroll_inner">
                        <div class="thumb_user">
                            <div class="profile_thumb">
                                <img src="imgs/thumb02.jpg" alt="프로필사진">
                            </div>
                            <div class="detail">
                                <div class="id">kind_tigerrrr</div>
                                <div class="time">1시간 전</div>
                            </div>
                        </div>
                    </div>
                </article>

                <article class="recommend">
                    <header class="reco_header">
                        <div>회원님을 위한 추천</div>
                        <div class="more">모두 보기</div>
                    </header>

                    <div class="thumb_user">
                        <div class="profile_thumb">
                            <img src="imgs/thumb02.jpg" alt="프로필사진">
                        </div>
                        <div class="detail">
                            <div class="id">kind_tigerrrr</div>
                            <div class="time">1시간 전</div>
                        </div>
                    </div>
                </article>
            </div>


        </div>
    </section>

{% include "post/script_ajax.html" %}

{% endblock %}

post/templates/post/post_new.html
{% extends 'post/layout.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/new_post.css' %}">
{% endblock %}





{% block content %}
<div id="main_container">
    <div class="post_form_container">
        <form action="#" class="post_form" method="post" enctype="multipart/form-data">
            <div class="title">
                New Post
            </div>
            <div class="preview">
                <label for="id_photo">
                    <div class="upload">
                        <div class="post_btn">
                            <div class="plus_icon">
                                <span></span>
                                <span></span>
                            </div>
                            <p>포스트 이미지 추가</p>
                            <canvas id="imageCanvas"></canvas>
                        </div>
                    </div>
                </label>
            </div>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="submit_btn" value="저장">
        </form>
    </div>
</div>

<script>
var fileInput = document.querySelector("#id_photo")
fileInput.addEventListener('change', handleImage);
var canvas = document.getElementById('imageCanvas')
var ctx = canvas.getContext('2d');
    
function handleImage(e){
    var reader = new FileReader();
    reader.onload = function(event){
        var img = new Image();
        img.onload = function(){
            canvas.width = 300;
            canvas.height = 300;
            ctx.drawImage(img, 0, 0, 300, 300);
        };
        img.src = event.target.result;
    };
    reader.readAsDataURL(e.target.files[0]);
}
</script>














{% endblock %}

post/templates/post/script_ajax.html
<script type="text/javascript">
(function(){
    const delegation = document.querySelector('.contents_box');
    
    function delegationFunc(e) {
        let elem = e.target;
        
        console.log(elem);
        
        while(!elem.getAttribute('data-name')){
            elem = elem.parentNode;
            
            if(elem.nodeName == 'BODY'){
                elem = null;
                return;
            }
        }
        
        if (elem.matches('[data-name="heartbeat"]')){
            console.log('하트!');
            
            var pk = elem.getAttribute('name');
            console.log(pk);
            
            $.ajax({
                type: "POST",
                url: "{% url 'post:post_like' %}",
                data: { 'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: "json",
                success: function (reponse){
                    var likeCount = document.querySelector('#like-count-' + pk);
                    likeCount.innerHTML = '좋아요' + response.like_count + '개';
                },
                error: function (request, status, error) {
                    alert('에러');
                },
            });
            
        }else if(elem.matches('[data-name="bookmark"]')){
            console.log('북마크!');
            
            var pk = elem.getAttribute('name');
            console.log(pk);
            
            $.ajax({
                type: "POST",
                url: "{% url 'post:post_bookmark' %}",
                data: { 'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: "json",
                success: function (reponse){
                    var bookmarkCount = document.querySelector('#bookmark-count-' + pk);
                    bookmarkCount.innerHTML = '북마크' + response.bookmark_count + '개';
                },
                error: function (request, status, error) {
                    alert('에러');
                },
            }); 
        }else if (elem.matches('[data-name="comment"]')){
            console.log('새 댓글');
            var pk = elem.getAttribute('name');
            var content = document.querySelector('#add-comment-post'+pk+'>input[type=text]').value;
            console.log(content);
            
            if(content.length > 140){
                alert("댓글은 최대 140자 입력 가능합니다. 현재 글자수 :"+content.length);
                return;
            }
        }
        
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
        elem.classList.toggle('on');
    }
    
    delegation.addEventListener('click', delegationFunc);
})();






</script>